### ISSUE TITLE
the evaluated file went wrong

### ISSUE THREAD

**Issue by 131231412313** [williamshen-nz/STRIPS-HGN#3]
```
(stripshgn) joyce@JOYCE:~/STRIPS-HGN/src$ ./eval.py -d domain.pddl -p instance-1.pddl -c epoch\=33-val_loss\=0.3228.ckpt/

2024-09-19 16:27:57 strips_hgn.utils.logging_setup INFO     Writing logs to /home/joyce/STRIPS-HGN/results/eval-strips-hgn-2024-09-19T16:27:57.001902/strips_hgn.log
2024-09-19 16:27:57 strips_hgn.utils.helpers INFO     Experiment results directory: /home/joyce/STRIPS-HGN/results/eval-strips-hgn-2024-09-19T16:27:57.001902
Traceback (most recent call last):
  File "./eval.py", line 60, in <module>
    eval_wrapper(args=parse_and_validate_evaluation_args())
  File "./eval.py", line 51, in eval_wrapper
    wrap_method(
  File "/home/joyce/STRIPS-HGN/src/strips_hgn/utils/wrapper.py", line 46, in wrap_method
    dump_args(args, experiments_dir, f"{experiment_type}_args.json")
  File "/home/joyce/STRIPS-HGN/src/strips_hgn/utils/helpers.py", line 121, in dump_args
    json.dump(args.__dict__, open(args_fname, "w"), indent=2, cls=ArgsEncoder)
  File "/home/joyce/miniconda3/envs/stripshgn/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/joyce/miniconda3/envs/stripshgn/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/joyce/miniconda3/envs/stripshgn/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/joyce/miniconda3/envs/stripshgn/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/joyce/STRIPS-HGN/src/strips_hgn/utils/json_encoders.py", line 22, in default
    if issubclass(o, AbstractFeatureMapper):
  File "/home/joyce/miniconda3/envs/stripshgn/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

Could you help me again?After I finished training and got the ckpt model file, the evaluated file went wrong.

Does the command in terminal cause the bug? I don't know...

**Comment by williamshen-nz** [comment]
I'm not sure if this will work but you could try updating `json_encoders.py`. Basically arg 1 is not a type, so the check might fail.

```python
class ArgsEncoder(JSONEncoder):
    """ For encoding command line arguments """

    def default(self, o: Any) -> Any:
        if isinstance(o, type) and issubclass(o, AbstractFeatureMapper):
            return o.name()
        elif isinstance(o, Enum):
            return o.value
        else:
            return super().default(o)
```

**Comment by 131231412313** [comment]
thank you for your generous help, this problem has been solved!
